name: Eightest-Linux

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Eightest: ${{ github.workspace }}

    steps:
    - name: "Download project"
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: "Setup Ubuntu (Dev)"
      run: |
        cmake --version
        gcc --version
        g++ --version
        ldd --version

    - name: "Regenerate and Rebuild project"
      run: |
        cd "${Eightest}"
        rm -rf Intermediate
        cmake -S . -B Intermediate -G Ninja \
          -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_BUILD_TYPE=Release \
          -DEIGHTEST_RUN_MODULE=Eightest
        cmake --build Intermediate --parallel

    - name: "Package and Upload project"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}
        path: |
          ${{ env.Eightest }}/Binaries

    - name: "Test project"
      run: |
        cd "${Eightest}/Binaries"
        ./EightestLauncher
